spring.application.name=resfood-api

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/banco?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
