spring.application.name=resfood-api

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/banco?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=create

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.mvc.log-resolved-exception=true
spring.web.resources.add-mappings=false
